Repository VoteDream/spring-vote-21st, pull requests merged in 2025-06, with the labels that each got.

#2 [FIX] refresh token cookie & test code
  build.gradle
  src/main/java/vote/dream/server/domain/user/controller/UserController.java
  src/main/java/vote/dream/server/domain/user/service/AuthService.java
  src/main/java/vote/dream/server/domain/vote/controller/VoteController.java
  src/main/java/vote/dream/server/global/apiPayload/status/ErrorStatus.java
  src/test/java/vote/dream/server/AuthControllerTest.java
  src/test/java/vote/dream/server/MockConfig.java
  src/test/java/vote/dream/server/TestSecurityConfig.java
Labels: bug, enhancement

#4 [FEAT] [FIX] vote관련 컨트롤러 + 서비스 수정 / team 엔티티 추가 / 더미 데이터 생성 코드 추가
  src/main/java/vote/dream/server/domain/vote/controller/VoteController.java
  src/main/java/vote/dream/server/domain/vote/entity/Team.java
  src/main/java/vote/dream/server/domain/vote/repository/TeamRepository.java
  src/main/java/vote/dream/server/domain/vote/service/VoteService.java
  src/main/java/vote/dream/server/global/config/VoteDataInitializer.java
Labels: enhancement, question

#5 [FIX] [REFACTOR] 정렬 기능 추가 + 필요 없는 주석 삭제 + 더미데이터 생성 시 데이터 간 매핑 추가
  src/main/java/vote/dream/server/domain/vote/controller/VoteController.java
  src/main/java/vote/dream/server/domain/vote/entity/VoteItem.java
  src/main/java/vote/dream/server/domain/vote/repository/VoteItemRepository.java
  src/main/java/vote/dream/server/domain/vote/service/VoteService.java
  src/main/java/vote/dream/server/global/config/VoteDataInitializer.java
Labels: bug, enhancement

#6 [FIX] user enumtype fix
  src/main/java/vote/dream/server/domain/user/entity/User.java
  src/main/resources/application.yml
Labels: bug

#8 [FIX] 투표 결과 조회(results)와 투표 항목 조회(items)의 response json을 PARTLEADER: 2차원 배열, DEMODAY: 1차원 배열로 변환하는 로직 구현
  src/main/java/vote/dream/server/domain/vote/controller/VoteController.java
  src/main/java/vote/dream/server/domain/vote/service/VoteService.java
Labels: enhancement
